name: moliyachi
description: "Mebel sexi uchun moliyaviy ERP tizimi"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.6.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  fl_chart: ^0.66.0
  flutter_login: ^5.0.0
  font_awesome_flutter: ^10.7.0
  
  # YANGI QO'SHILGAN KUTUBXONA:
  rolling_bottom_bar: ^0.2.0


  # 1. Supabase (Baza)
  supabase_flutter: ^2.6.0

  # 2. Formatlash (Sana va Summa)
  intl: ^0.19.0

  # 3. Ikonkalar
  cupertino_icons: ^1.0.6

  # 4. Grafiklar (Charts) - MANA BU YERGA QO'SHDIK
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
