name: hisobcheck
description: "Mebel sexi uchun moliyaviy ERP tizimi"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Asosiy baza
  supabase_flutter: ^2.6.0

  # Formatlash (Sana va Summa)
  intl: ^0.19.0

  # Ikonkalar
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0

  # Grafiklar
  fl_chart: ^0.66.0

  # Login animatsiyasi
  flutter_login: ^5.0.0

  # Aylanuvchi pastki menyu
  rolling_bottom_bar: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
