name: Android APK Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Kodni yuklab olish
    - uses: actions/checkout@v4

    # 2. Java o'rnatish
    - name: Java o'rnatish
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    # 3. Flutter o'rnatish
    - name: Flutter o'rnatish
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
    # 4. ðŸ”¥ MUHIM: Android fayllarini yaratish
    # Bu buyruq avtomatik ravishda 'flutter pub get' ni ham ishga tushiradi
    - name: Create Flutter Project
      run: flutter create --project-name hisobcheck . --platforms android

    # 5. Kutubxonalarni majburan FLUTTER orqali yuklash
    # (Oldingi xatoni tuzatish qismi)
    - name: Kutubxonalarni yuklash
      run: flutter pub get

    # 6. APK build qilish
    - name: APK build qilish
      run: flutter build apk --release --no-tree-shake-icons

    # 7. Faylni saqlab olish
    - name: APKni saqlab olish (Artifacts)
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
        compression-level: 0
