name: Android APK Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Java o'rnatish
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Flutter o'rnatish
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0' # Yoki eng yangi versiya

    - name: Kutubxonalarni yuklash
      run: flutter pub get

    - name: APK build qilish
      run: flutter build apk --release --no-tree-shake-icons

    - name: APKni saqlab olish (Artifacts)
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
