name: Android APK Yasash

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Java o'rnatish
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Flutter o'rnatish
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'

    # 1. Pubspec faylni to'g'irlash
    - name: Loyiha nomini to'g'irlash
      run: |
        sed -i 's/name: Hisobcheck/name: hisobcheck/g' pubspec.yaml

    - name: Kutubxonalarni yuklash
      run: |
        flutter pub get
        flutter pub add supabase_flutter
        flutter pub add intl
        flutter pub add shared_preferences

    # 2. Android papkasini yangilash
    - name: Android papkasini yangilash (Fix Gradle)
      run: |
        rm -rf android
        flutter create --project-name hisobcheck --platforms android .

    # --- [ ENG MUHIM QISM: INTERNETNI YOQISH ] ---
    - name: Internet ruxsatini qo'shish
      run: |
        # AndroidManifest.xml ichiga ruxsat yozish
        sed -i 's|<application|<uses-permission android:name="android.permission.INTERNET"/>\n    <application|g' android/app/src/main/AndroidManifest.xml

    - name: APK yasash
      run: flutter build apk --release

    - name: APKni saqlash (Artifacts)
      uses: actions/upload-artifact@v4
      with:
        name: aristokrat-mebel-apk
        path: build/app/outputs/flutter-apk/app-release.apk
