name: Mening Kodimni Ishlatish

# Qachon ishga tushsin? (Har safar kod o'zgarganda)
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Repozitoriy kodini yuklab olish
    - name: Kodlarni tekshirish (Checkout)
      uses: actions/checkout@v3

    # 2. Pythonni o'rnatish
    - name: Pythonni o'rnatish
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    # 3. Asosiy faylni ishga tushirish
    - name: Dasturni ishga tushirish
      run: python main.py
